export const data = [
  {
    id: 1,
    title: "Destiny Education Zone",
    image: "/assets/project/destiny education Zone.png",
    description: "Details about project one.",
    description1: "Additional details about project one.",
    videoImg: "/assets/project/destiny education Zone.png",
    github: "https://github.com/example/destiny-education-zone",
    live: "https://destinyeducationzone.com",
    nestedData: {
      images: [
        "/assets/project/destiny education Zone.png",
        "/assets/project/destiny education Zone.png",
        "/assets/project/destiny education Zone.png",
        "/assets/project/destiny education Zone.png",
        "/assets/project/destiny education Zone.png",
        "/assets/project/destiny education Zone.png",
      ],
      video: "https://www.youtube.com/embed/examplevideo",
    },
    nestedSkill: {
      html: "HTML",
      css: "CSS",
      javascript: "JavaScript",
      react: "React",
      tailwind: "Tailwind CSS",
      apiIntegration: "API Integration",
    },
  },
  // {
  //   id: 2,
  //   title: "Another Project Title",
  //   image: "/assets/project/another-project-image.png",
  //   description: "Details about project two.",
  //   description1: "Additional details about project two.",
  //   videoImg: "/assets/project/another-project-image.png",
  //   github: "https://github.com/example/another-project",
  //   live: "https://anotherproject.com",
  //   nestedData: {
  //     images: [
  //       "/assets/project/another-project-image1.png",
  //       "/assets/project/another-project-image2.png",
  //       "/assets/project/another-project-image3.png",
  //     ],
  //     video: "https://www.youtube.com/embed/examplevideo2",
  //   },
  //   nestedSkill: {
  //     html: "HTML",
  //     css: "CSS",
  //     javascript: "JavaScript",
  //     react: "React",
  //     tailwind: "Tailwind CSS",
  //     apiIntegration: "API Integration",
  //   },
  // },
  {
    id: 3,
    title: "Destiny Education Zone",
    image: "/assets/project/destiny education Zone.png",
    description: "Details about project two Details about project twoDetails about project twoDetails about project twoDetails about project twoDetails about project two",
    description1: "Details about project two Details about project twoDetails about project twoDetails about project twoDetails about project twoDetails about project two",
    videoImg: "/assets/project/destiny education Zone.png",
    github: "https://github.com/example/destiny-education-zone",
    live: "https://destinyeducationzone.com",
    nestedData: {
      images: [
        "/assets/project/destiny education Zone.png",
        "/assets/project/destiny education Zone.png",
        "/assets/project/destiny education Zone.png",
        "/assets/project/destiny education Zone.png",
        "/assets/project/destiny education Zone.png",
        "/assets/project/destiny education Zone.png",
      ],
      video: "https://www.youtube.com/embed/examplevideo",
    },
    nestedSkill: {
      html: "HTML",
      css: "CSS",
      javascript: "JavaScript",
      react: "React",
      tailwind: "Tailwind CSS",
      apiIntegration: "API Integration",
    },
  },
  // New project entry
  // {
  //   id: 4,
  //   title: "New Project Title",
  //   image: "/assets/project/new-project-image.png",
  //   description: "Details about the new project.",
  //   description1: "Additional details about the new project.",
  //   videoImg: "/assets/project/new-project-image.png",
  //   github: "https://github.com/example/new-project",
  //   live: "https://newproject.com",
  //   nestedData: {
  //     images: [
  //       "/assets/project/new-project-image1.png",
  //       "/assets/project/new-project-image2.png",
  //       "/assets/project/new-project-image3.png",
  //     ],
  //     video: "https://www.youtube.com/embed/newexamplevideo",
  //   },
  //   nestedSkill: {
  //     html: "HTML",
  //     css: "CSS",
  //     javascript: "JavaScript",
  //     react: "React",
  //     tailwind: "Tailwind CSS",
  //     apiIntegration: "API Integration",
  //     nodejs: "Node.js", // Example of an additional skill
  //   },
  // },
];
